// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2KKpLi27KxhFDJ7sLzK3wxjtuMHLy4dI',
    appId: '1:786888900127:web:53f42f427d0877de1a9f2a',
    messagingSenderId: '786888900127',
    projectId: 'taski-1e5df',
    authDomain: 'taski-1e5df.firebaseapp.com',
    storageBucket: 'taski-1e5df.firebasestorage.app',
    measurementId: 'G-RG1995KK93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1n-HP1BJQvx_elpEgSD35vRXehYd4Htc',
    appId: '1:786888900127:android:bfd7e3653ff675611a9f2a',
    messagingSenderId: '786888900127',
    projectId: 'taski-1e5df',
    storageBucket: 'taski-1e5df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACAMj5dSGJkcfZ3ta60jHysNyGurM9iWg',
    appId: '1:786888900127:ios:4e3dc1e90836ffbf1a9f2a',
    messagingSenderId: '786888900127',
    projectId: 'taski-1e5df',
    storageBucket: 'taski-1e5df.firebasestorage.app',
    iosBundleId: 'com.example.taski',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACAMj5dSGJkcfZ3ta60jHysNyGurM9iWg',
    appId: '1:786888900127:ios:4e3dc1e90836ffbf1a9f2a',
    messagingSenderId: '786888900127',
    projectId: 'taski-1e5df',
    storageBucket: 'taski-1e5df.firebasestorage.app',
    iosBundleId: 'com.example.taski',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2KKpLi27KxhFDJ7sLzK3wxjtuMHLy4dI',
    appId: '1:786888900127:web:40ca3e3c9af5f9591a9f2a',
    messagingSenderId: '786888900127',
    projectId: 'taski-1e5df',
    authDomain: 'taski-1e5df.firebaseapp.com',
    storageBucket: 'taski-1e5df.firebasestorage.app',
    measurementId: 'G-ZM8EY8BMC7',
  );
}
